### ISSUE TITLE
laravel-multitenancy-route-model-binding.md

### ISSUE THREAD

**Issue by RFreij** [Lloople/davidllop.com#4]
Hi
I've just read your post and I was thinking, why not use a policy with a edit method and check there if the tenant ID matches logged in user? The **can** Middleware on the route would be enough without overwriting any methods. 

Also the way it is handled now returns a 404 when a user that is not the tenant tries to edit the article, however the user tries to do something that is not allowed, so shouldn't it be a 403? (hence policy). 

I'm interested in your opinion on this matter. 

Kind regards, 

Roy

**Comment by Lloople** [comment]
Hi Roy,

Thanks to take your time to reach me.

Yes you're right, policies will also work in this case. It's more like a personal preference. I like to deal with permissions once the tenant is configured for the whole app, because each tenant can also have different users, and there's where I'll use Policies.

For example I can have a tenant called Eric L. Barnes. And it has three companies to manage articles, `laravel-news`, `laravel-jobs` and `dotdev.co`.

He will manage articles like this for each project:

```
myapp.test/laravel-news/articles/3
myapp.test/laravel-jobs/articles/4
myapp.test/dotdev-co/articles/5
```

So, if he tries to access article 5 from a different company rather than dotdev.co, a 404 will be thrown using this Route Model Binding overriding method.

In the case of trying to spuff some url to edit content owned by another user I prefer to display a 404 instead of 403, because that articles doesn't belongs to that tenant also means that tenant doesn't know what that article is. For me it's like isolating each tenant in it's own environment.

Let me know if I didn't explained it very well.

Kind regards,

David
